name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 15.206.160.41
          username: ubuntu
          key: ${{ secrets.PRIVATE_SECRET_KEY }}
          port: 22
          script: ./deploy.sh